phonebook/config/routes.rb
Rails.application.routes.draw do

  root to: 'home#index'
  get 'home/index'

  resources :contacts do
    resources :phone_numbers, except: :show, path_names: {edit: ""}
    resources :addresses, except: :show, path_names: {edit: ""}
  end	

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

phonebook/app/controllers/addresses_controller.rb
class AddressesController < ApplicationController
  before_action :set_address, only: [:show, :edit, :update, :destroy]
  before_action :set_contact , only: [:new, :create, :edit,:update]

  # GET /addresses
  # GET /addresses.json
  def index
    @addresses = Address.all
  end

  # GET /addresses/1
  # GET /addresses/1.json
  def show
  end

  # GET /addresses/new
  def new
    @address = @contact.address.new
  end

  # GET /addresses/1/edit
  def edit
  end

  # POST /addresses
  # POST /addresses.json
  def create
    @address = @contact.address.new(address_params)

    respond_to do |format|
      if @address.save
        format.html { redirect_to contact_path @address.contact_id , notice: 'Address was successfully created.' }
        format.json { render :show, status: :created, location: @address }
      else
        format.html { render :new }
        format.json { render json: @address.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /addresses/1
  # PATCH/PUT /addresses/1.json
  def update
    respond_to do |format|
      if @address.update(address_params)
        format.html { redirect_to contact_path @address.contact_id, notice: 'Address was successfully updated.' }
        format.json { render :show, status: :ok, location: @address }
      else
        format.html { render :edit }
        format.json { render json: @address.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /addresses/1
  # DELETE /addresses/1.json
  def destroy
    @address.destroy
    respond_to do |format|
      format.html { redirect_to contact_path @address.contact_id, notice: 'Address was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contact
      @contact = Contact.find(params[:contact_id])
    end

    def set_address
      @address = Address.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def address_params
      params.require(:address).permit(:contact_id, :label, :address)
    end
end

phonebook/app/helpers/addresses_helper.rb
module AddressesHelper
end

phonebook/app/views/addresses/_form.html.erb
<%= form_with(model: [@contact,address] , local: true) do |form| %>
  <% if address.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(address.errors.count, "error") %> prohibited this address from being saved:</h2>

      <ul>
      <% address.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

   <div class="form-group row">
    <%= form.label :label , class: "col-sm-2 col-form-label"%>
    <div class="col-sm-10">
      <%= form.text_field :label, id: :address_label  , class: "form-control input-width"%>
    </div>
  </div>

   <div class="form-group row">
    <%= form.label :address , class: "col-sm-2 col-form-label"%>
    <div class="col-sm-10">
      <%= form.text_area :address, id: :address_address  , class: "form-control input-width"%>
    </div>
  </div>

  <div class="actions">
    <%= form.submit "Save", class: "btn btn-primary" %>
  </div>
<% end %>

phonebook/app/views/addresses/edit.html.erb
<%= link_to 'Back', contact_path(@contact.id) , class: "badge badge-info" %>
<h4 class="card-title"><%= "Editing Address for #{@contact.first_name}" %></h4>

<%= render 'form', address: @address %>

phonebook/app/views/addresses/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Addresses</h1>

<table>
  <thead>
    <tr>
      <th>Contact</th>
      <th>Label</th>
      <th>Address</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @addresses.each do |address| %>
      <tr>
        <td><%= address.contact %></td>
        <td><%= address.label %></td>
        <td><%= address.address %></td>
        <td><%= link_to 'Show', address %></td>
        <td><%= link_to 'Edit', edit_address_path(address) %></td>
        <td><%= link_to 'Destroy', address, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Address', new_address_path %>

phonebook/app/views/addresses/new.html.erb
<%= link_to 'Back', contact_path(@contact.id) , class: "badge badge-info" %>
<h4 class="card-title"><%= "New Address for #{@contact.first_name}" %></h4>

<%= render 'form', address: @address %>

phonebook/app/views/addresses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Contact:</strong>
  <%= @address.contact %>
</p>

<p>
  <strong>Label:</strong>
  <%= @address.label %>
</p>

<p>
  <strong>Address:</strong>
  <%= @address.address %>
</p>

<%= link_to 'Edit', edit_address_path(@address) %> |
<%= link_to 'Back', addresses_path %>