phonebook/config/routes.rb
Rails.application.routes.draw do

  root to: 'home#index'
  get 'home/index'

  resources :contacts do
    resources :phone_numbers, except: :show, path_names: {edit: ""}
    resources :addresses, except: :show, path_names: {edit: ""}
  end	

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

phonebook/app/models/contact.rb
class Contact < ApplicationRecord
	has_many :address, dependent: :destroy 
	has_many :phone_number, dependent: :destroy 

	validates :first_name, :last_name, :email, :presence => true
	validates_format_of :email , :with => /\A^(?:[a-z0-9._%+-]+@)(?:(?!\d+\.)[\w\-]{1,63}\.)+(?:[a-z]{2,})$\z/i,
    message: 'must be valid email address'

    def full_name
      first_name + " " + last_name
    end
end

phonebook/app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :set_contact, only: [:show, :edit, :update, :destroy]

  # GET /contacts
  # GET /contacts.json
  def index
    @contacts = Contact.all
  end

  # GET /contacts/1
  # GET /contacts/1.json
  def show
  end

  # GET /contacts/new
  def new
    @contact = Contact.new
  end

  # GET /contacts/1/edit
  def edit
  end

  # POST /contacts
  # POST /contacts.json
  def create
    @contact = Contact.new(contact_params)

    respond_to do |format|
      if @contact.save
        format.html { redirect_to @contact, notice: 'Contact was successfully created.' }
        format.json { render :show, status: :created, location: @contact }
      else
        format.html { render :new }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contacts/1
  # PATCH/PUT /contacts/1.json
  def update
    respond_to do |format|
      if @contact.update(contact_params)
        format.html { redirect_to @contact, notice: 'Contact was successfully updated.' }
        format.json { render :show, status: :ok, location: @contact }
      else
        format.html { render :edit }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contacts/1
  # DELETE /contacts/1.json
  def destroy
    @contact.destroy
    respond_to do |format|
      format.html { redirect_to contacts_url, notice: 'Contact was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contact
      @contact = Contact.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def contact_params
      params.require(:contact).permit(:first_name, :last_name, :email, :notes)
    end
end

phonebook/app/helpers/contacts_helper.rb
module ContactsHelper
end

phonebook/app/views/contacts/_form.html.erb
<%= form_with(model: contact, local: true) do |form| %>
  <% if contact.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(contact.errors.count, "error") %> prohibited this contact from being saved:</h2>

      <ul>
      <% contact.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group row">
    <%= form.label :first_name , class: "col-sm-2 col-form-label"%>
    <div class="col-sm-10">
      <%= form.text_field :first_name, id: :contact_first_name , class: "form-control input-width"%>
    </div>
  </div>

  <div class="form-group row">
    <%= form.label :last_name , class: "col-sm-2 col-form-label"%>
    <div class="col-sm-10">
      <%= form.text_field :last_name, id: :contact_last_name , class: "form-control input-width"%>
    </div>  
  </div>

  <div class="form-group row">
    <%= form.label :email , class: "col-sm-2 col-form-label"%>
    <div class="col-sm-10">
      <%= form.text_field :email, id: :contact_email , class: "form-control input-width"%>
    </div>  
  </div>

  <div class="form-group row">
    <%= form.label :notes , class: "col-sm-2 col-form-label"%>
    <div class="col-sm-10">
      <%= form.text_area :notes, id: :contact_notes , class: "form-control input-width"%>
    </div>
  </div>

  <div class="actions ">
    <%= form.submit "Save", class: "btn btn-primary" %>
  </div>
<% end %>

phonebook/app/views/contacts/edit.html.erb
<%= link_to 'Back', contacts_path , class: "badge badge-info" %>
<%= link_to 'Show', @contact  , class: "badge badge-info" %>
<h2 class="card-title">Editing Contact</h2>
<%= render 'form', contact: @contact %>

phonebook/app/views/contacts/index.html.erb
<p id="notice"><%= notice %></p>

<h2 class="card-title">Contacts</h2>
<%= link_to 'Add Contact', new_contact_path  , class: "badge badge-primary"%>

<table class="table" style="width:30%;">
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @contacts.each do |contact| %>
      <tr>
        <td><%= contact.full_name %></td>
        <td><%= link_to 'Show', contact %></td>
        <td><%= link_to 'Edit', edit_contact_path(contact) %></td>
        <td><%= link_to 'Destroy', contact, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

phonebook/app/views/contacts/new.html.erb
<%= link_to 'Back', contacts_path , class: "badge badge-info" %>
<h2 class="card-title">New Contact</h2>

<%= render 'form', contact: @contact %>

phonebook/app/views/contacts/show.html.erb
<p id="notice"><%= notice %></p>
<%= link_to 'Edit', edit_contact_path(@contact)  , class: "badge badge-info"%>
<%= link_to 'Back', contacts_path  , class: "badge badge-info"%>
<ul class="list-group">
  
</ul>
<div class="container">
  <dl class="dl-horizontal">
    <dt>First name:</dt>
    <dd><%= @contact.first_name %></dd>
    <dt>Last name:</dt>
    <dd><%= @contact.last_name %></dd>
    <dt>Email:</dt>
    <dd><%= @contact.email %></dd>
    <dt>Notes:</dt>
    <dd><%= @contact.notes %></dd>
    <dt>Address</dt>
    <dd><%= link_to 'Add Address', new_contact_address_path(@contact) , class: "badge badge-info" %></dd>
    <dd>
      <table class="table borderless input-width">
        <% @contact.address.each do |contact| %>
          <tr>
            <td> <%= "#{contact.label}" %> </td>
            <td> <%= contact.address %></td>
            <td> <%= link_to 'Edit', edit_contact_address_path(@contact,contact) ,class: "badge badge-info"%></td>
            <td> <%= link_to 'Destroy', contact_address_path(@contact,contact), method: :delete, data: { confirm: 'Are you sure?' } , class: "badge badge-info"%></td>
          </tr>
        <% end %>  
      </table>
    </dd>

    <dt>Contact Number(s)</dt>
    <dd><%= link_to 'Add Contact Number', new_contact_phone_number_path(@contact) , class: "badge badge-info"%></dd>
    <dd>
      <table class="table input-width">
        <% @contact.phone_number.each do |contact| %>
          <tr>
            <td> <%= "#{contact.label} : " %> </td>
            <td> <%= contact.phone_number %></td>
            <td> <%= link_to 'Edit', edit_contact_phone_number_path(@contact,contact) , class: "badge badge-info" %> </td>
            <td><%= link_to 'Destroy', contact_phone_number_path(@contact,contact), method: :delete, data: { confirm: 'Are you sure?' }  , class: "badge badge-info"%> </td>
          </tr>
        <% end %>  
      </table>
    </dd>
  </dl>
</div>